export const PATHS = {
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  HOME: "/home",
  ABOUT: "/about",
  CART: "/cart",
  PRODUCT_NO_SUB: "/products/:categoryId/:productId",
  PRODUCT_WITH_SUB: "/products/:categoryId/:subcategoryId/:productId",
  CATALOG_CATEGORY: "/catalog/:categoryId",
  CATALOG_SUBCATEGORY: "/catalog/:categoryId/:subcategoryId",
  ADMIN_CATALOG: "/catalog/admin",
  ADMIN_ORDERS: "/orders/admin",
  REGISTRATION_ORDERS: "/registration/orders",
  PROFILE_ME: "/profile/me",
  PROFILE_ORDERS: "/profile/orders",
  PROFILE_PRODUCTS_IN_ORDER: "/profile/orders/:orderId",

  SEARCH: "/search",
  NOT_FOUND: "*",
  ACCESS_DENIED: "/access-denied",
  PRIVACY_POLICY: "/privacy-policy",
  USER_AGREEMENT: "/user-agreement",
};
