export const PATHS = {
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  HOME: "/home",
  ABOUT: "/about",
  CART: "/cart",
  PRODUCT_NO_SUB: "/products/:categoryId/:productId",
  PRODUCT_WITH_SUB: "/products/:categoryId/:subcategoryId/:productId",
  CATALOG_CATEGORY: "/catalog/:categoryId",
  CATALOG_SUBCATEGORY: "/catalog/:categoryId/:subcategoryId",
  PROFILEME: "/profile/me",
  PROFILEORDERS: "/profile/orders",
  NOT_FOUND: "*",
  ACCESS_DENIED: "/access-denied",
  PRIVACY_POLICY: "/privacy-policy",
  USER_AGREEMENT: "/user-agreement",
};
