"""delete unique name in subcategories

Revision ID: 017fd3ecc58c
Revises: a25b58b881c3
Create Date: 2026-03-22 19:18:38.897025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017fd3ecc58c'
down_revision: Union[str, Sequence[str], None] = 'a25b58b881c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcategories_name'), table_name='subcategories')
    op.create_index(op.f('ix_subcategories_name'), 'subcategories', ['name'], unique=False)
    op.create_unique_constraint('uq_subcategory_name_category', 'subcategories', ['name', 'category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subcategory_name_category', 'subcategories', type_='unique')
    op.drop_index(op.f('ix_subcategories_name'), table_name='subcategories')
    op.create_index(op.f('ix_subcategories_name'), 'subcategories', ['name'], unique=True)
    # ### end Alembic commands ###
