"""change status in order

Revision ID: 29893ff50510
Revises: 627766ba8949
Create Date: 2026-03-29 13:21:28.321928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29893ff50510'
down_revision: Union[str, Sequence[str], None] = '627766ba8949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "status",
        server_default=None,
        existing_type=sa.Boolean(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "status",
        server_default=sa.false(),
        existing_type=sa.Boolean(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
