"""change tables categories and subcategories

Revision ID: 37cc7a5bf0f6
Revises: 66df2ecab3dc
Create Date: 2026-02-15 17:51:25.184834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cc7a5bf0f6'
down_revision: Union[str, Sequence[str], None] = '66df2ecab3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
