"""add discount_percent in cart model

Revision ID: 4506f0bb06f7
Revises: 4cb00fc82a55
Create Date: 2026-03-12 12:13:36.669039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4506f0bb06f7'
down_revision: Union[str, Sequence[str], None] = '4cb00fc82a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('discount_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'discount_percent')
    # ### end Alembic commands ###
