"""add discount_percent to products

Revision ID: 4cb00fc82a55
Revises: 94a012cf0099
Create Date: 2026-03-10 17:29:00.640754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb00fc82a55'
down_revision: Union[str, Sequence[str], None] = '94a012cf0099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_percent')
    # ### end Alembic commands ###
