"""change tables categories and subcategories

Revision ID: 56c58c2dcaaa
Revises: da6848f62b31
Create Date: 2026-02-15 17:00:34.519408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c58c2dcaaa'
down_revision: Union[str, Sequence[str], None] = 'da6848f62b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategories', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'subcategories', ['category_id'])
    op.create_foreign_key(None, 'subcategories', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.drop_constraint(None, 'subcategories', type_='unique')
    op.drop_column('subcategories', 'category_id')
    # ### end Alembic commands ###
