"""feat cascade delete in cart

Revision ID: 581a4d2c8d06
Revises: 29893ff50510
Create Date: 2026-04-26 15:56:07.097639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581a4d2c8d06'
down_revision: Union[str, Sequence[str], None] = '29893ff50510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_product_id_fkey'), 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key(op.f('cart_product_id_fkey'), 'cart', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
