"""add field legal_name in table users

Revision ID: 5f412439c76b
Revises: 38cfcb095353
Create Date: 2026-02-16 14:45:27.023924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f412439c76b'
down_revision: Union[str, Sequence[str], None] = '38cfcb095353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('legal_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'legal_name')
    # ### end Alembic commands ###
