"""add cascade in product model

Revision ID: 773c34e6ccb9
Revises: 017fd3ecc58c
Create Date: 2026-03-24 14:37:40.794539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773c34e6ccb9'
down_revision: Union[str, Sequence[str], None] = '017fd3ecc58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_subcategory_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'subcategories', ['subcategory_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_subcategory_id_fkey'), 'products', 'subcategories', ['subcategory_id'], ['id'])
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
