"""delete fields in codes

Revision ID: 7d74288bcf7c
Revises: b00a0621c118
Create Date: 2026-02-04 20:15:09.329207

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d74288bcf7c'
down_revision: Union[str, Sequence[str], None] = 'b00a0621c118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codes', 'attempts')
    op.drop_column('codes', 'is_used')
    op.drop_column('codes', 'user_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codes', sa.Column('user_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('codes', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('codes', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
