"""delete unique inn

Revision ID: 93d388572802
Revises: 7d74288bcf7c
Create Date: 2026-02-04 20:18:25.674408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d388572802'
down_revision: Union[str, Sequence[str], None] = '7d74288bcf7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_inn'), table_name='users')
    op.create_index(op.f('ix_users_inn'), 'users', ['inn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_inn'), table_name='users')
    op.create_index(op.f('ix_users_inn'), 'users', ['inn'], unique=True)
    # ### end Alembic commands ###
