"""add category_id in CartModel

Revision ID: a25b58b881c3
Revises: 3f56f7bfdb08
Create Date: 2026-03-19 15:06:33.585461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25b58b881c3'
down_revision: Union[str, Sequence[str], None] = '3f56f7bfdb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cart', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'category_id')
    # ### end Alembic commands ###
