"""add fields user_data in codes

Revision ID: b00a0621c118
Revises: a4002adbcfda
Create Date: 2026-02-04 19:21:21.516477

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b00a0621c118'
down_revision: Union[str, Sequence[str], None] = 'a4002adbcfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codes', sa.Column('user_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codes', 'user_data')
    # ### end Alembic commands ###
