"""change tables categories and subcategories

Revision ID: b278a457deb2
Revises: 56c58c2dcaaa
Create Date: 2026-02-15 17:45:10.278765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b278a457deb2'
down_revision: Union[str, Sequence[str], None] = '56c58c2dcaaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subcategories_category_id_key'), 'subcategories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('subcategories_category_id_key'), 'subcategories', ['category_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
