"""change user model

Revision ID: f070b029ea4c
Revises: 773c34e6ccb9
Create Date: 2026-03-24 16:11:53.091052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f070b029ea4c'
down_revision: Union[str, Sequence[str], None] = '773c34e6ccb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.String(), nullable=True))
    
    # Устанавливаем значение 'legal' для всех существующих записей
    op.execute("UPDATE users SET user_type = 'legal' WHERE user_type IS NULL")
    
    # Делаем колонку NOT NULL
    op.alter_column('users', 'user_type', nullable=False)
    
    # Добавляем остальные колонки
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
